version: "3.8"
services:
  gradle:
    build:
      context: .
      dockerfile: ./docker/gradle/Dockerfile
  tomcat:
    build:
      context: .
      dockerfile: ./docker/tomcat/Dockerfile
    ports:
      - 8000
      - 8080