/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java library project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.7/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the java-library plugin for API and implementation separation.
    `java-library`
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

configurations.all {
    resolutionStrategy.eachDependency {
        if (requested.group == "org.ow2.asm") {
            useVersion("9.5")
        }
    }
}
dependencies {
    // This dependency is used internally, and not exposed to consumers on their own compile classpath.
    implementation("org.parboiled:parboiled-java:1.4.1")

    // Use JUnit Jupiter for testing.
    testImplementation(libs.junit.jupiter)
    testImplementation("org.apache.commons:commons-lang3:3.14.0")
    testRuntimeOnly("org.junit.platform:junit-platform-launcher")

    // Use Groovy for demo scripts
    implementation("org.apache.groovy:groovy:4.0.21")
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}

tasks.register<JavaExec>("runConverterDemo") {
    classpath = sourceSets["main"].runtimeClasspath
    mainClass = "groovy.ui.GroovyMain"
    args = listOf("src/script/groovy/converterDemo.groovy")
}

tasks.register<JavaExec>("runCollectorDemo") {
    classpath = sourceSets["main"].runtimeClasspath
    mainClass = "groovy.ui.GroovyMain"
    args = listOf("src/script/groovy/collectorDemo.groovy")
}